arch: "x86_64"
images:
- location: "/tmp/lima/example-x86_64-uefi.img"
  arch: "x86_64"
mounts:
- location: "/tmp/lima"
  writable: true
mountType: 9p
ssh:
  localPort: 0
firmware:
  legacyBIOS: false
video:
  display: none
containerd:
  system: false
  user: false
provision:
- mode: dependency
  skipDefaultDependencyResolution: true
  script: |
    #!/bin/sh
    set -eu
